language: python
# make it explicit that we favor the new container-based travis workers
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.5"
install: pip install -r requirements.txt
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6eb6ecea5b0f73499506
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
